items/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.item_form,name='item_insert'),
    path('<int:id>/', views.item_form,name='item_update'),
    path('delete/<int:id>/', views.item_delete,name='item_delete'),
    path('list/', views.item_list,name='item_list'),
    path('history/', views.history_service_form,name='history_insert'),
    path('history/update/<str:item_history_service_id>/', views.history_service_form,name='history_update'),
    path('history/delete/<str:item_history_service_id>/', views.history_service_delete,name='history_delete'),
    path('history/list/', views.history_service_list,name='history_list'),
    path('history/detail/<str:item_history_service_id>', views.history_service_detail,name='history_detail'),
    path('borrow/export/pdf/', views.pdf_report_item_history, name='export_report_item_history'),
    path('history/export/pdf/<str:item_history_service_id>/', views.pdf_item_history, name='export_item_history'),
]

warehouse_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('item/', include('items.urls')),
    path('employee/', include('employee.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

items/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 50)

    def __str__(self):
        return self.name

class Item(models.Model):
    item_name = models.CharField(max_length = 200)
    item_code = models.CharField(max_length = 8)
    item_merk = models.CharField(max_length = 100)
    category = models.ForeignKey(Category,on_delete = models.CASCADE)
    item_picture = models.ImageField(blank=True,upload_to='album_item/',default='album_item/no-image.jpg')
    active = models.BooleanField('Active or not', blank=True, default=True)

    def __str__(self):
        return self.item_name

class ItemHistoryService(models.Model):
    # AutoIncrementID
    def increment_service_number():
        last_service = ItemHistoryService.objects.all().order_by('item_history_service_id').last()

        if not last_service:
            return 'SERV-'+ str(datetime.now().strftime('%d%m%Y-'))+'0000'

        service_id = last_service.item_history_service_id
        service_int = service_id[14:18]
        new_service_int = int(service_int)+1
        new_service_id = 'SERV-'+ str(datetime.now().strftime('%d%m%Y-'))+str(new_service_int).zfill(4)

        return new_service_id

    item_history_service_id = models.CharField(max_length=20,primary_key=True,unique=True,default=increment_service_number)
    item_name = models.ForeignKey('items.Item',on_delete=models.CASCADE,related_name='items_set')
    service_by = models.ForeignKey('employee.Employee',on_delete=models.CASCADE,related_name='employee_set')
    service_date = models.DateField()
    detail_service = models.TextField(max_length = 800)
    picture = models.ImageField(blank=True,upload_to='album_history/',default='album_history/no-image.jpg')

    def __str__(self):
        return self.item_history_service_id

items/forms.py
from django import forms
from .models import Item,ItemHistoryService

class ItemForms(forms.ModelForm):
    item_picture = forms.FileField()

    class Meta:
        model = Item
        fields = ('item_name', 'item_code', 'item_merk', 'category', 'item_picture')
        labels = {
            'item_name':'Item Name',
            'item_code':'Item Code',
            'item_merk':'Item Merk',
            'item_picture':'Item Picture',
        }
    
    def __init__(self,*args,**kwargs):
        super(ItemForms,self).__init__(*args,**kwargs)
        self.fields['category'].empty_label = "Select"
        self.fields['item_code'].required = True

class DateInput(forms.DateInput):
    input_type = 'date'

class ItemHistoryServiceForm(forms.ModelForm):
    service_date = forms.DateField()
    picture = forms.FileField()
    class Meta:
        model = ItemHistoryService
        fields = ('item_history_service_id','item_name','service_by','service_date','detail_service','picture')
        labels = {
            'item_history_service_id':'Item History Service ID',
            'item_name':'Item Name',
            'service_by':'Service By',
            'service_date':'Service Date',
            'detail_service':'Detail Service',
            'picture':'Insert Picture',
        }
        widgets = {
            'service_date':forms.DateInput(attrs={'class':'MyDate'}),
        }

    def __init__(self,*args,**kwargs):
        super(ItemHistoryServiceForm,self).__init__(*args,**kwargs)
        self.fields['item_name'].empty_label="Select"

items/views.py
from django.shortcuts import render,redirect
from .forms import ItemForms, ItemHistoryServiceForm
from .models import Item, ItemHistoryService
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponse,HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO
import sys

# Create your views here.

def item_list(request):
    # context = {'item_list':Item.objects.all()}
    item_list = Item.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(item_list,10)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request,"item/item_list.html",{'item_list':items})

def item_form(request,id = 0):
    if request.method=="GET":
        if id==0:
            form=ItemForms()

        else:
            item = Item.objects.get(pk = id)
            form = ItemForms(instance=item)
        return render(request,"item/item_form.html",{'form':form})

    else:
        if id==0:
            form=ItemForms(request.POST,request.FILES)
        else:
            item = Item.objects.get(pk = id)
            form = ItemForms(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item_picture=form.cleaned_data['item_picture']
            form.save()
        return redirect('/item/list')

def item_delete(request,id):
    item = Item.objects.get(pk = id)
    item.delete() 
    return redirect('/item/list')

def history_service_list(request):
    # context = {
    # 'history_service_list': ItemHistoryService.objects.all(),
    # }

    history_service_list = ItemHistoryService.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(history_service_list,10)
    try:
        history_service = paginator.page(page)
    except PageNotAnInteger:
        history_service = paginator.page(1)
    except EmptyPage:
        history_service = paginator.page(paginator.num_pages)
    
    return render(request,"history_service/item_history_service_list.html",{'history_service_list':history_service})

def history_service_form(request,item_history_service_id = 0):
    
    if request.method=='GET':
        if item_history_service_id==0:
            form=ItemHistoryServiceForm()

        else:
            try :
                history_service = ItemHistoryService.objects.get(pk = item_history_service_id)
            except ItemHistoryService.DoesNotExist:
                history_service = None             
            form = ItemHistoryServiceForm(instance=history_service)
        return render(request,"history_service/item_history_service_form.html",{'form':form})

    else:
        if item_history_service_id==0:
            form=ItemHistoryServiceForm(request.POST,request.FILES)
        else:
            history_service = ItemHistoryService.objects.get(pk = item_history_service_id)
            form = ItemHistoryServiceForm(request.POST, request.FILES, instance=history_service)
        if form.is_valid():
            picture=form.cleaned_data['picture']
            form.save()
        return redirect('/item/history/list')

def history_service_delete(request,item_history_service_id):
    history_service = ItemHistoryService.objects.get(pk = item_history_service_id)
    history_service.delete() 
    return redirect('/item/history/list')

def history_service_detail(request,item_history_service_id):
    context = {
        'history' : ItemHistoryService.objects.get(pk = item_history_service_id)
    }
    return render(request,'history_service/item_history_service_detail.html',context)

def render_to_pdf(template_src,context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode('utf8')),result)
    if not pdf.err:
        return HttpResponse(result.getvalue(),content_type='application/pdf')
    return None

def pdf_report_item_history(request):
    histories = ItemHistoryService.objects.select_related('item_name', 'service_by')
    params = {
        'histories': histories,
        'request': request,
    }
    return render_to_pdf('history_service/pdf_report_item_history_service.html',params)

def pdf_item_history(request,item_history_service_id):
    histories = ItemHistoryService.objects.get(pk=item_history_service_id)
    params = {
        'history': histories,
        'request': request,
    }
    return render_to_pdf('history_service/pdf_item_history_service.html',params)

items/templates/history_service/item_history_service_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Item History Service Detail</h2>
</div>
<br>
<div class="container">
    <table class="table table-borderless table-responsive">
        <tbody>
            <tr class="d-flex">
                <td class="col-4">Item History Service ID</td>
                <td>{{history.item_history_service_id}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Item Code</td>
                <td>{{history.item_name.item_code}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Item Name</td>
                <td>{{history.item_name}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Item Merk</td>
                <td>{{history.item_name.item_merk}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Item Category</td>
                <td>{{history.item_name.category}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Employee NIK</td>
                <td>{{history.service_by.employee_nik}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Service By</td>
                <td>{{history.service_by.fullname}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Detail Service</td>
                <td>{{history.detail_service}}</td>
            </tr>
            <tr class="d-flex">
                <td class="col-4">Picture Service</td>
                <td class="col-12"><img src="{{history.picture.url}}" style="max-width: 60%; max-height: 50%;"></td>
            </tr>
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-md-8">
    </div>
    <div class="col-md-4">
        <a href="{% url 'history_list' %}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Back to list
        </a>
    </div>
</div>
{% endblock content %}

items/templates/history_service/item_history_service_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Item History Service Form</h2>
</div>
<form action="" method="post" autocomplete="off" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.item_history_service_id|as_crispy_field}}
    {{form.item_name|as_crispy_field}}
    {{form.service_by|as_crispy_field}}
    {{form.detail_service|as_crispy_field}}
    <div class="form-group row">
        <div class="col-sm-8">
            <label>Service Date*</label>
            <div>
                <input class="form-control" type="date" id="id_service_date" name="service_date" class="MyDate">
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-8">
            <label>Picture*</label>
            <div class="custom-file mb-3">
                <input class="custom-file-input" type="file" id="id_picture" name="picture">
                <label class="custom-file-label" for="id_picture">Choose file</label>
                <div>
                    <label class="text-danger">*Must upload landscape image</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-paper-plane"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'history_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}

items/templates/history_service/item_history_service_list.html
{% extends "base.html" %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Item History Service List</h2>
</div>
<table class="table table-responsive table-striped w-auto medium">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Item History Service ID</td>
            <td>Item Name</td>
            <td>Category Item</td>
            <td>Service By</td>
            <td>Service Date</td>
            <td style="width: 14%">
                <a href="{% url 'history_insert' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
            <td style="width: 8%">
              <a href="{% url 'export_report_item_history' %}" target="_blank" class="btn btn-outline-success">
                <i class='fas fa-download' style='color:green'></i> All
              </a>
          </td>
        </tr>
    </thead>
    <tbody>
        {% for history in history_service_list %}
        <tr>
            <td>{{history.item_history_service_id}}</td>
            <td>{{history.item_name.item_name}}</td>
            <td>{{history.item_name.category}}</td>
            <td>{{history.service_by.fullname}}</td>
            <td>{{history.service_date}}</td>
            <td>
                <a href="{% url 'history_detail' history.item_history_service_id %}" class="btn text-secondary px-10">
                    <i class="fa fa-search fa-lg"></i>
                </a>
                <a href="{% url 'history_update' history.item_history_service_id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg"></i>
                </a>
                <form action="{% url 'history_delete' history.item_history_service_id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </button>
                </form>
            </td>
            <td>
              <a href="{% url 'export_item_history' history.item_history_service_id %}" class="btn text-secondary px-0" target="_blank">
                <i class='fas fa-download btn btn-outline-success'  style='font-size:16px;color:green'></i>
              </a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if history_service_list.has_other_pages %}
  <ul class="pagination">
    {% if history_service_list.has_previous %}
      <li><a href="?page={{ history_service_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in history_service_list.paginator.page_range %}
      {% if history_service_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if history_service_list.has_next %}
      <li><a href="?page={{ history_service_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock content %}

items/templates/history_service/pdf_item_history_service.html
<html>
    <head>
        <title>Item History Service Form Download</title>
        <meta charset="utf-8">
        <style type="text/css">
            @page {
                size: A4;
                margin: 1cm;
            }
    
            img {
                width: 200px;
                border-radius: 8px;
            }

            h2 {
                text-align: center;
                font-size: 18px;
            }

            tbody {
                font-size: 16px;
            }

            table {
                table-layout: fixed;
                width:50px;
                border-collapse: collapse;
            }

            tbody tr:nth-child(odd) {
                background: #eee;
            }
    
        </style>
    </head>
    <body>
        <img src="../img/23.png" / >
        <hr>
        <div>
            <h2>Item History Service Form</h2>
            <div>
                <table>
                    <tbody>
                        <tr>
                            <td><strong>Item History Service ID</strong></td>
                            <td>{{history.item_history_service_id}}</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><strong>Name</strong></td>
                            <td>{{history.item_name.item_name}}</td>
                        </tr>
                        <tr>
                            <td><strong>Category Item</strong></td>
                            <td>{{history.item_name.category}}</td>
                        </tr>
                        <tr>
                            <td><strong>Service By</strong></td>
                            <td>{{history.service_by.fullname}}</td>
                        </tr>
                        <tr>
                            <td><strong>Service Date</strong></td>
                            <td>{{history.service_date}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
          </div>        
    </body>
    <footer>

    </footer>
</html>

items/templates/history_service/pdf_report_item_history_service.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Item History Service Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
            border-collapse: collapse;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
            border: 1px solid black;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
            background-color:black;
            color: white;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table .table {
            background-color: #fff;
        }

        .card-header {
            text-align: center;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>Item History Service Report</h2>
            </div>
            <table class="table table-bordered table-striped">
                <thead class="thead-dark">
                <tr>
                    <th>Item History Service ID</th>
                    <th>Item Name</th>
                    <th>Category Item</th>
                    <th>Service By</th>
                    <th>Service Date</th>
                </tr>
                </thead>
                <tbody>
                {% for history in histories %}
                    <tr>
                        <td>{{history.item_history_service_id}}</td>
                        <td>{{history.item_name.item_name}}</td>
                        <td>{{history.item_name.category}}</td>
                        <td>{{history.service_by.fullname}}</td>
                        <td>{{history.service_date}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>