items/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.item_form,name='item_insert'),
    path('<int:id>/', views.item_form,name='item_update'),
    path('delete/<int:id>/', views.item_delete,name='item_delete'),
    path('list/', views.item_list,name='item_list'),
    path('history/', views.history_service_form,name='history_insert'),
    path('history/update/<str:item_history_service_id>/', views.history_service_form,name='history_update'),
    path('history/delete/<str:item_history_service_id>/', views.history_service_delete,name='history_delete'),
    path('history/list/', views.history_service_list,name='history_list'),
    path('history/detail/<str:item_history_service_id>', views.history_service_detail,name='history_detail'),
    path('borrow/export/pdf/', views.pdf_report_item_history, name='export_report_item_history'),
    path('history/export/pdf/<str:item_history_service_id>/', views.pdf_item_history, name='export_item_history'),
]

warehouse_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('item/', include('items.urls')),
    path('employee/', include('employee.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

items/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 50)

    def __str__(self):
        return self.name

class Item(models.Model):
    item_name = models.CharField(max_length = 200)
    item_code = models.CharField(max_length = 8)
    item_merk = models.CharField(max_length = 100)
    category = models.ForeignKey(Category,on_delete = models.CASCADE)
    item_picture = models.ImageField(blank=True,upload_to='album_item/',default='album_item/no-image.jpg')
    active = models.BooleanField('Active or not', blank=True, default=True)

    def __str__(self):
        return self.item_name

class ItemHistoryService(models.Model):
    # AutoIncrementID
    def increment_service_number():
        last_service = ItemHistoryService.objects.all().order_by('item_history_service_id').last()

        if not last_service:
            return 'SERV-'+ str(datetime.now().strftime('%d%m%Y-'))+'0000'

        service_id = last_service.item_history_service_id
        service_int = service_id[14:18]
        new_service_int = int(service_int)+1
        new_service_id = 'SERV-'+ str(datetime.now().strftime('%d%m%Y-'))+str(new_service_int).zfill(4)

        return new_service_id

    item_history_service_id = models.CharField(max_length=20,primary_key=True,unique=True,default=increment_service_number)
    item_name = models.ForeignKey('items.Item',on_delete=models.CASCADE,related_name='items_set')
    service_by = models.ForeignKey('employee.Employee',on_delete=models.CASCADE,related_name='employee_set')
    service_date = models.DateField()
    detail_service = models.TextField(max_length = 800)
    picture = models.ImageField(blank=True,upload_to='album_history/',default='album_history/no-image.jpg')

    def __str__(self):
        return self.item_history_service_id

items/forms.py
from django import forms
from .models import Item,ItemHistoryService

class ItemForms(forms.ModelForm):
    item_picture = forms.FileField()

    class Meta:
        model = Item
        fields = ('item_name', 'item_code', 'item_merk', 'category', 'item_picture')
        labels = {
            'item_name':'Item Name',
            'item_code':'Item Code',
            'item_merk':'Item Merk',
            'item_picture':'Item Picture',
        }
    
    def __init__(self,*args,**kwargs):
        super(ItemForms,self).__init__(*args,**kwargs)
        self.fields['category'].empty_label = "Select"
        self.fields['item_code'].required = True

class DateInput(forms.DateInput):
    input_type = 'date'

class ItemHistoryServiceForm(forms.ModelForm):
    service_date = forms.DateField()
    picture = forms.FileField()
    class Meta:
        model = ItemHistoryService
        fields = ('item_history_service_id','item_name','service_by','service_date','detail_service','picture')
        labels = {
            'item_history_service_id':'Item History Service ID',
            'item_name':'Item Name',
            'service_by':'Service By',
            'service_date':'Service Date',
            'detail_service':'Detail Service',
            'picture':'Insert Picture',
        }
        widgets = {
            'service_date':forms.DateInput(attrs={'class':'MyDate'}),
        }

    def __init__(self,*args,**kwargs):
        super(ItemHistoryServiceForm,self).__init__(*args,**kwargs)
        self.fields['item_name'].empty_label="Select"

items/views.py
from django.shortcuts import render,redirect
from .forms import ItemForms, ItemHistoryServiceForm
from .models import Item, ItemHistoryService
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.http import HttpResponse,HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO
import sys

# Create your views here.

def item_list(request):
    # context = {'item_list':Item.objects.all()}
    item_list = Item.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(item_list,10)
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request,"item/item_list.html",{'item_list':items})

def item_form(request,id = 0):
    if request.method=="GET":
        if id==0:
            form=ItemForms()

        else:
            item = Item.objects.get(pk = id)
            form = ItemForms(instance=item)
        return render(request,"item/item_form.html",{'form':form})

    else:
        if id==0:
            form=ItemForms(request.POST,request.FILES)
        else:
            item = Item.objects.get(pk = id)
            form = ItemForms(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item_picture=form.cleaned_data['item_picture']
            form.save()
        return redirect('/item/list')

def item_delete(request,id):
    item = Item.objects.get(pk = id)
    item.delete() 
    return redirect('/item/list')

def history_service_list(request):
    # context = {
    # 'history_service_list': ItemHistoryService.objects.all(),
    # }

    history_service_list = ItemHistoryService.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(history_service_list,10)
    try:
        history_service = paginator.page(page)
    except PageNotAnInteger:
        history_service = paginator.page(1)
    except EmptyPage:
        history_service = paginator.page(paginator.num_pages)
    
    return render(request,"history_service/item_history_service_list.html",{'history_service_list':history_service})

def history_service_form(request,item_history_service_id = 0):
    
    if request.method=='GET':
        if item_history_service_id==0:
            form=ItemHistoryServiceForm()

        else:
            try :
                history_service = ItemHistoryService.objects.get(pk = item_history_service_id)
            except ItemHistoryService.DoesNotExist:
                history_service = None             
            form = ItemHistoryServiceForm(instance=history_service)
        return render(request,"history_service/item_history_service_form.html",{'form':form})

    else:
        if item_history_service_id==0:
            form=ItemHistoryServiceForm(request.POST,request.FILES)
        else:
            history_service = ItemHistoryService.objects.get(pk = item_history_service_id)
            form = ItemHistoryServiceForm(request.POST, request.FILES, instance=history_service)
        if form.is_valid():
            picture=form.cleaned_data['picture']
            form.save()
        return redirect('/item/history/list')

def history_service_delete(request,item_history_service_id):
    history_service = ItemHistoryService.objects.get(pk = item_history_service_id)
    history_service.delete() 
    return redirect('/item/history/list')

def history_service_detail(request,item_history_service_id):
    context = {
        'history' : ItemHistoryService.objects.get(pk = item_history_service_id)
    }
    return render(request,'history_service/item_history_service_detail.html',context)

def render_to_pdf(template_src,context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode('utf8')),result)
    if not pdf.err:
        return HttpResponse(result.getvalue(),content_type='application/pdf')
    return None

def pdf_report_item_history(request):
    histories = ItemHistoryService.objects.select_related('item_name', 'service_by')
    params = {
        'histories': histories,
        'request': request,
    }
    return render_to_pdf('history_service/pdf_report_item_history_service.html',params)

def pdf_item_history(request,item_history_service_id):
    histories = ItemHistoryService.objects.get(pk=item_history_service_id)
    params = {
        'history': histories,
        'request': request,
    }
    return render_to_pdf('history_service/pdf_item_history_service.html',params)

items/templates/item/item_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Item Register Form</h2>
</div>
<form action="" method="post" autocomplete="off" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.item_name|as_crispy_field}}
    {{form.item_code|as_crispy_field}}
    {{form.item_merk|as_crispy_field}}
    <div class="row">
        <div class="col-md-8">
            {{form.category|as_crispy_field}}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-8">
            <label>Item Picture*</label>
            <div class="custom-file mb-3">
                <input class="custom-file-input" type="file" id="id_item_picture" name="item_picture">
                <label class="custom-file-label" for="id_item_picture">Choose file</label>
                <div>
                    <label class="text-danger">*Must upload landscape image</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-paper-plane"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'item_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}

items/templates/item/item_list.html
{% extends "base.html" %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Items List</h2>
</div>
<table class="table table-striped">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Item Code</td>
            <td>Item Name</td>
            <td>Item Merk</td>
            <td>Category</td>
            <td>
                <a href="{% url 'item_insert' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for item in item_list %}
        <tr>
            <td>{{item.item_code}}</td>
            <td>{{item.item_name}}</td>
            <td>{{item.item_merk}}</td>
            <td>{{item.category}}</td>
            
            <td>
                <button class="btn text-secondary px-10"  data-toggle="modal" data-target="#myModal{{item.pk}}{{forloop.counter0}}" type="button">
                    <i class="fas fa-camera fa-lg"></i>
                </button>
                <!-- The Modal -->
            <div class="modal" id="myModal{{item.pk}}{{forloop.counter0}}">
                <div class="modal-dialog">
                <div class="modal-content">
            
                    <!-- Modal Header -->
                    <div class="modal-header">
                    <h4 class="modal-title">Item Picture</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
            
                    <!-- Modal body -->
                    <div class="modal-body">
                        <img src="{{item.item_picture.url}}" style="max-width: 80%; max-height: 70%;">
                    </div>
            
                    <!-- Modal footer -->
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
            
                </div>
                </div>
            </div>
                <a href="{% url 'item_update' item.id %}" class="btn text-secondary px-0">
                    <i class="far fa-edit fa-lg"></i>
                </a>
                <form action="{% url 'item_delete' item.id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if item_list.has_other_pages %}
  <ul class="pagination">
    {% if item_list.has_previous %}
      <li><a href="?page={{ item_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in item_list.paginator.page_range %}
      {% if item_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if item_list.has_next %}
      <li><a href="?page={{ item_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock content %}