employee/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.employee_form,name='employee_insert'),
    path('<int:employee_nik>/', views.employee_form,name='employee_update'),
    path('delete/<int:id>/', views.employee_delete,name='employee_delete'),
    path('list/', views.employee_list,name='employee_list'),
    path('login/', views.login_view,name='login_view'),
    path('register/', views.register,name='register'),
    path('borrow/', views.borrow_form,name='borrow_insert'),
    path('borrow/<int:id>/', views.borrow_form,name='borrow_update'),
    path('borrow/delete/<int:id>/', views.borrow_delete,name='borrow_delete'),
    path('borrow/list/', views.borrow_list,name='borrow_list'),
    path('borrow/export/pdf/', views.pdf_view, name='export_data'),
    path('borrow/export/pdf/<int:id>/', views.pdf_borrow_view, name='export_data_borrow'),
]

items/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.item_form,name='item_insert'),
    path('<int:id>/', views.item_form,name='item_update'),
    path('delete/<int:id>/', views.item_delete,name='item_delete'),
    path('list/', views.item_list,name='item_list'),
    path('history/', views.history_service_form,name='history_insert'),
    path('history/update/<str:item_history_service_id>/', views.history_service_form,name='history_update'),
    path('history/delete/<str:item_history_service_id>/', views.history_service_delete,name='history_delete'),
    path('history/list/', views.history_service_list,name='history_list'),
    path('history/detail/<str:item_history_service_id>', views.history_service_detail,name='history_detail'),
    path('borrow/export/pdf/', views.pdf_report_item_history, name='export_report_item_history'),
    path('history/export/pdf/<str:item_history_service_id>/', views.pdf_item_history, name='export_item_history'),
]

warehouse_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('item/', include('items.urls')),
    path('employee/', include('employee.urls')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

employee/models.py
from django.db import models
from items.models import Item
from django.core.validators import MaxValueValidator
from django.contrib.auth.models import User,AbstractBaseUser

# Create your models here.

class Position(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Employee(models.Model):
    sex_choices = {
        ('','Select'),
        ('Female', 'Female'),
        ('Male', 'Male'),
    }

    division_choices = {
        ('','Select'),
        ('Manajemen Direksi','Manajemen Direksi'),
        ('HSE', 'HSE'),
        ('Lapangan', 'Lapangan'),
        ('Keuangan', 'Keuangan'),
    }
        
    fullname = models.CharField(max_length=200)
    employee_nik = models.BigIntegerField(primary_key=True)
    position = models.ForeignKey(Position,on_delete=models.CASCADE)
    division = models.CharField(max_length=200,choices=division_choices)
    sex = models.CharField(max_length=50,choices=sex_choices, blank=False, default='')
    address = models.CharField(max_length=300)

    def __str__(self):
        return self.fullname

class EmployeeAccount(models.Model):
    account = models.OneToOneField(User,on_delete=models.CASCADE)
    worker = models.ForeignKey(Employee,on_delete=models.CASCADE)
    username = models.CharField('username',unique = True,max_length=255)
    email = models.EmailField('email address',unique = True)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.worker.fullname

class BorrowTransaction(models.Model):
    employee_nik = models.ForeignKey(Employee,on_delete=models.CASCADE,related_name='employes')
    borrow_date = models.DateField()
    item_name = models.ForeignKey(Item,on_delete=models.CASCADE,related_name='items')
    project_location = models.CharField(max_length=300)
    return_date = models.DateField(null = True, blank = True)

    def __str__(self):
        return self.id

employee/forms.py
from django import forms
from .models import Employee,EmployeeAccount,BorrowTransaction
from django.contrib.auth.forms import UserCreationForm
from items.models import Item

class Employee_Form(forms.ModelForm):
    
    class Meta:
        model = Employee
        fields = ('fullname', 'employee_nik', 'position', 'division', 'sex', 'address')
        labels = {
            'fullname':'Fullname',
            'employee_nik':'NIK',
            'division':'Division',
            'address':'Address',
            'sex':'Sex',
        }

    def __init__(self,*args,**kwargs):
        super(Employee_Form,self).__init__(*args,**kwargs)
        self.fields['position'].empty_label = "Select"
        self.fields['sex'].empty_label = None
        self.fields['division'].empty_label = None

class CreateUserEmployee(UserCreationForm):
    username = forms.CharField(required = True)
    email = forms.EmailField(required = True)
    class Meta:
        model = EmployeeAccount
        fields = ("username","email","password1","password2")
    def save(self,commit=True):
        user = super(CreateUserEmployee,self).save(commit=False)
        user.username = self.cleaned_data["username"]
        if commit:
            user.save()
        return user

class DateInput(forms.DateInput):
    input_type = 'date'

class BorrowForm(forms.ModelForm):
    borrow_date = forms.DateField()

    class Meta:
        model = BorrowTransaction
        fields = ('employee_nik','borrow_date','item_name', 'project_location', 'return_date')
        labels = {
            'employee_nik':'Employee Name',
            'item_name':'Item Name',
            'project_location':'Project Location',
        }
        widgets = {
            'borrow_date':forms.DateInput(attrs={'class':'MyDate'}),
        }
    def __init__(self,*args,**kwargs):
        super(BorrowForm,self).__init__(*args,**kwargs)
        self.fields['item_name'].queryset = Item.objects.filter(active = True)
        self.fields['return_date'].disabled=True

class ReturnForm(forms.ModelForm):
    return_date = forms.DateField(required=True)

    class Meta:
        model = BorrowTransaction
        fields = ('employee_nik','borrow_date','item_name', 'project_location', 'return_date')
        labels = {
            'employee_nik':'Employee Name',
            'item_name':'Item Name',
            'project_location':'Project Location',
            'borrow_date':'Borrow Date',
        }
        widgets = {
            'return_date':forms.DateInput(attrs={'class':'MyDateReturn'}),
        }
    def __init__(self,*args,**kwargs):
        super(ReturnForm,self).__init__(*args,**kwargs)
        self.fields['item_name'].disabled = True
        self.fields['employee_nik'].disabled = True
        self.fields['project_location'].disabled = True
        self.fields['borrow_date'].disabled = True

employee/views.py
from django.shortcuts import render,redirect
from .models import Employee,EmployeeAccount,BorrowTransaction
from .forms import Employee_Form,CreateUserEmployee,BorrowForm,ReturnForm
from django.contrib.auth import authenticate,logout,login
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from items.models import Item
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
import csv
from django.http import HttpResponse,HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO
import sys

# Create your views here.

def employee_list(request):
    # context = {'employee_list':Employee.objects.all()}
    employee_list = Employee.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(employee_list,10)
    try:
        employees = paginator.page(page)
    except PageNotAnInteger:
        employees = paginator.page(1)
    except EmptyPage:
        employees = paginator.page(paginator.num_pages)
    return render(request,"employee/employee_list.html",{'employee_list':employees})

def employee_form(request,employee_nik=0,id=0):
    if request.method=='GET':
        if employee_nik==0:
            form=Employee_Form()

        else:
            employee = Employee.objects.get(pk = employee_nik)
            form = Employee_Form(instance=employee)
        return render(request,"employee/employee_form.html",{'form':form})

    else:
        if employee_nik==0:
            form=Employee_Form(request.POST)
        else:
            employee = Employee.objects.get(pk = employee_nik)
            form = Employee_Form(request.POST, instance=employee)
        if form.is_valid():
            form.save()
        return redirect('/employee/list')

def employee_delete(request,id):
    employee = Employee.objects.get(pk = id)
    employee.delete() 
    return redirect('/employee/list')

def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(request=request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username,password = password)
            if user is not None:
                login(request,user)
                return redirect('employee/list')
            else:
                messages.error(request,'Username or Password Incorrect')
        else:
            messages.error(request,"Invalid Username or Password")
    form = AuthenticationForm()
    return render(request = request,template_name = 'employee/login.html',context = {"form":form})

def logout_view(request):
    logout(request)
    return redirect('/login')

def register(request):
    if request.method=='POST':
        form = CreateUserEmployee(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request,user)
            return redirect("employee/list")
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])
            return render(request=request,template_name = "employee/register.html",context = {"form":form})
    form = CreateUserEmployee
    return render(request=request,template_name = "employee/register.html",context = {"form":form})

def borrow_list(request):
    
    # context = {
    # 'borrow_list': BorrowTransaction.objects.all(), 
    # }
    borrow_list = BorrowTransaction.objects.all()
    page = request.GET.get('page',1)
    paginator = Paginator(borrow_list,10)
    try:
        borrows = paginator.page(page)
    except PageNotAnInteger:
        borrows = paginator.page(1)
    except EmptyPage:
        borrows = paginator.page(paginator.num_pages)
    
    return render(request,"borrow/borrow_list.html",{'borrow_list':borrows})

def borrow_form(request,id = 0):
    if request.method=='GET':
        if id==0:
            form=BorrowForm()
            return render(request,"borrow/borrow_form.html",{'form':form})
        else:
            borrow = BorrowTransaction.objects.get(pk = id)
            form = ReturnForm(instance=borrow)
            borrow.item_name.active = True
            borrow.item_name.save()
            item = Item.objects.get(pk = form['item_name'].value())
            item.active = True
            item.save()
            return render(request,"borrow/return_form.html",{'form':form})
        
    else:
        if id==0:
            form=BorrowForm(request.POST)
            insert = True
        else:
            borrow = BorrowTransaction.objects.get(pk = id)
            form = ReturnForm(request.POST, instance=borrow)
            insert=False
        if insert == True and form.is_valid():
            form.save()
            item = Item.objects.get(pk = form['item_name'].value())
            item.active = False
            item.save()
        if form.is_valid():
            form.save()
        return redirect('/employee/borrow/list')

def borrow_delete(request,id):
    borrow = BorrowTransaction.objects.get(pk = id)
    borrow.delete() 
    return redirect('/employee/borrow/list')

# def file_load_view(request):
#     response = HttpResponse(content_type='text/csv')
#     response['Content-Disposition'] = 'attatchment; filename="report_borrow.csv"'
#     writer = csv.writer(response)
#     writer.writerow(['Employee NIK', 'Employee Name', 'Item Name', 'Item Code', 'Project Location', 'Borrow Date', 'Return Date'])
#     borrows = BorrowTransaction.objects.select_related('employee_nik', 'item_name')
#     borrows = borrows.values_list('employee_nik_id', 'employee_nik__fullname', 'item_name__item_name', 'item_name__item_code', 'project_location', 'borrow_date', 'return_date')
#     for borrow in borrows:
#         writer.writerow(borrow)
#     return response

def render_to_pdf(template_src,context_dict={}):
    template = get_template(template_src)
    html = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode('utf8')),result)
    if not pdf.err:
        return HttpResponse(result.getvalue(),content_type='application/pdf')
    return None

def pdf_view(request):
    borrows = BorrowTransaction.objects.select_related('employee_nik', 'item_name')
    params = {
        'borrows': borrows,
        'request': request,
    }
    return render_to_pdf('borrow/pdf.html',params)

def pdf_borrow_view(request,id):
    borrows = BorrowTransaction.objects.get(pk=id)
    params = {
        'borrow': borrows,
        'request': request,
    }
    return render_to_pdf('borrow/pdf_borrow.html',params)

employee/templates/borrow/borrow_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Borrow Transaction Form</h2>
</div>
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{form.employee_nik|as_crispy_field}}
    {{form.item_name|as_crispy_field}}
    {{form.project_location|as_crispy_field}}
    <div class="form-group row">
        <div class="col-sm-4">
            <label>Borrow Date*</label>
            <div>
                <input class="form-control" type="date" value="{{borrow_date|date:'Y-m-d'}}" id="id_borrow_date" name="borrow_date" class="MyDate">
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4">
            <label>Return Date*</label>
            <div>
                <input class="form-control" type="date" readonly="True" id="id_return_date" name="return_date" class="MyDateReturn">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-paper-plane"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'borrow_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}

employee/templates/borrow/borrow_list.html
{% extends "base.html" %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Borrow Transaction List</h2>
</div>
<table class="table table-striped">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Employee NIK</td>
            <td>Employee Name</td>
            <td>Item Name</td>
            <td>Item Code</td>
            <td style="width: 18%">Project Location</td>
            <td>Borrow Date</td>
            <td>Return Date</td>
            <td style="width: 12%">
                <a href="{% url 'borrow_insert' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
            <td style="width: 8%">
              <a href="{% url 'export_data' %}" target="_blank" class="btn btn-outline-success">
                <i class='fas fa-download' style='color:green'></i> All
              </a>
          </td>
        </tr>
    </thead>
    <tbody>
        {% for borrow in borrow_list %}
        <tr>
            <td>{{borrow.employee_nik_id}}</td>
            <td>{{borrow.employee_nik.fullname}}</td>
            <td>{{borrow.item_name.item_name}}</td>
            <td>{{borrow.item_name.item_code}}</td>
            <td>{{borrow.project_location}}</td>
            <td>{{borrow.borrow_date}}</td>
            <td>{{borrow.return_date}}</td>
            <td>
                <a href="{% url 'borrow_update' borrow.id %}" class="btn text-secondary px-0">
                    <button type="button" class="btn btn-success btn-sm">Return</button>
                </a>
                <form action="{% url 'borrow_delete' borrow.id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </button>
                </form>
            </td>
            <td>
              <a href="{% url 'export_data_borrow' borrow.id %}" class="btn text-secondary px-0" target="_blank">
                <i class='fas fa-download btn btn-outline-success'  style='font-size:18px;color:green'></i>
              </a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if borrow_list.has_other_pages %}
  <ul class="pagination">
    {% if borrow_list.has_previous %}
      <li><a href="?page={{ borrow_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in borrow_list.paginator.page_range %}
      {% if borrow_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if borrow_list.has_next %}
      <li><a href="?page={{ borrow_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock content %}

employee/templates/borrow/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Borrow Transaction Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
            border-collapse: collapse;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
            border: 1px solid black;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
            background-color:black;
            color: white;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table tbody tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .table .table {
            background-color: #fff;
        }

        .card-header {
            text-align: center;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h1>Borrow Transaction Report</h1>
            </div>
                <table class="table">
                    <thead >
                    <tr >
                        <th>Employee NIK</th>
                        <th>Employee Name</th>
                        <th>Item Name</th>
                        <th>Item Code</th>
                        <th>Project Location</th>
                        <th>Borrow Date</th>
                        <th>Return Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for borrow in borrows %}
                        <tr>
                            <td>{{borrow.employee_nik_id}}</td>
                            <td>{{borrow.employee_nik.fullname}}</td>
                            <td>{{borrow.item_name.item_name}}</td>
                            <td>{{borrow.item_name.item_code}}</td>
                            <td>{{borrow.project_location}}</td>
                            <td>{{borrow.borrow_date}}</td>
                            <td>{{borrow.return_date}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
</body>
</html>

employee/templates/borrow/pdf_borrow.html
<html>
    <head>
        <title>Borrow Transaction Form Download</title>
        <meta charset="utf-8">
        <style type="text/css">
            @page {
                size: A4;
                margin: 1cm;
            }
    
            img {
                width: 200px;
                border-radius: 8px;
            }

            h2 {
                text-align: center;
                font-size: 18px;
            }

            tbody {
                font-size: 16px;
            }

            table {
                table-layout: fixed;
                width:50px;
                border-collapse: collapse;
            }

            tbody tr:nth-child(odd) {
                background: #eee;
            }
    
        </style>
    </head>
    <body>
        <img src="../img/23.png" / >
        <hr>
        <div>
            <h2>Borrow Transaction Form</h2>
            <div>
                <table>
                    <tbody>
                        <tr>
                            <td><strong>Employee NIK</strong></td>
                            <td>{{borrow.employee_nik_id}}</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><strong>Employee Name</strong></td>
                            <td>{{borrow.employee_nik.fullname}}</td>
                        </tr>
                        <tr>
                            <td><strong>Name</strong></td>
                            <td>{{borrow.item_name.item_name}}</td>
                        </tr>
                        <tr>
                            <td><strong>Item Code</strong></td>
                            <td>{{borrow.item_name.item_code}}</td>
                        </tr>
                        <tr>
                            <td><strong>Project Location</strong</td>
                            <td>{{borrow.project_location}}</td>
                        </tr>
                        <tr>
                            <td><strong>Borrow Date</strong></td>
                            <td>{{borrow.borrow_date}}</td>
                        </tr>
                        <tr>
                            <td><strong>Return Date</strong</td>
                            <td>{{borrow.return_date}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
          </div>        
    </body>
    <footer>

    </footer>
</html>

employee/templates/borrow/return_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="form-group" style="text-align: center; padding: 2%;">
    <h2 class="display-10">Borrow Transaction Form</h2>
</div>
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{form.employee_nik|as_crispy_field}}
    {{form.item_name|as_crispy_field}}
    {{form.project_location|as_crispy_field}}
    {{form.borrow_date|as_crispy_field}}
    <div class="form-group row">
        <div class="col-sm-4">
            <label>Return Date*</label>
            <div>
                <input class="form-control" type="date" id="id_return_date" name="return_date" class="MyDateReturn">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-paper-plane"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'borrow_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}